const INITIAL_SNAKE_LENGTH = 4
const DEFAULT_INTERVAL = 100
const SLOW_INTERVAL = 200
const ACCELERATED_INTERVAL = 50
const ACCELERATE_DURATION = 3000
const COOLDOWN_DURATION = 20000
const WEATHER_DURATION = 20000
const WEATHER_TYPES = ['sunny', 'rainy', 'snowy']

module.exports = {
  INITIAL_SNAKE_LENGTH,
  DEFAULT_INTERVAL,
  SLOW_INTERVAL,
  ACCELERATED_INTERVAL,
  ACCELERATE_DURATION,
  COOLDOWN_DURATION,
  WEATHER_DURATION,
  WEATHER_TYPES
}
